### ISSUE TITLE
MacOS nwjs Framework image not found

### ISSUE THREAD

**Issue by cryomi** [nwjs-community/nw-builder#443]
Hi all,
MacOS 10.12.4 Sierra
nw js 0.22.0 sdk

I did download/unpack with nw-builder https://github.com/nwjs-community/nw-builder.

`$ /0.22.0-sdk/osx64/nwjs.app/Contents/MacOS/nwjs`

```
dlopen /0.22.0-sdk/osx64/nwjs.app/Contents/MacOS/../Versions/58.0.3029.81/nwjs Framework.framework/nwjs Framework: 
dlopen(/0.22.0-sdk/osx64/nwjs.app/Contents/MacOS/../Versions/58.0.3029.81/nwjs Framework.framework/nwjs Framework, 257): 
image not found
Abort trap: 6
```

details in https://github.com/nwjs/nw.js/issues/5863

**Comment by tsnelson1** [comment]
I have investigated this issue as I was having the same issue, and here is what I have found to be the main issue. Extracting of the NWJS SDK (and this is exclusively with a change in v0.22.0 with the Chromium 58 migration), creates symbolic links that are invalid once nw-builder builds up the cache.

Here is where I found the problem (I hope this pasted link works, as I don't typically comment):
https://github.com/bower/decompress-zip/blob/master/lib/extractors.js#LC109
`return symlink(path.resolve(parent, linkTo), destination)`

This creates a symbolic link to the absolute path, which subsequently gets its underlying path renamed, and thus breaks.

**Comment by TatriX** [comment]
I have the same issue when I build the package from linux and then transfer it to a mac.

**Comment by cryomi** [comment]
@TatriX seems this package have no longer support, I moved to https://github.com/evshiron/nwjs-builder-phoenix, the have fix this issue quickly, set of issued described here https://github.com/nwjs-community/nw-builder/issues/443#issuecomment-298852092 perfectly.

**Comment by rogerwang** [comment]
@adam-lynch @DblK are you still maintaining this project? If yes, is there any plan on this issue? CC #444  #445

**Comment by adam-lynch** [comment]
Working on this

**Comment by adam-lynch** [comment]
Sorry about that. I've just published `3.2.1` which should fix this. Let me know if there is any problem with it.

**Comment by adam-lynch** [comment]
I should have said that you'll need to delete your cache directory. The bug resulted in something broken being cached. Thanks

**Comment by axtro** [comment]
Version 3.4.1 is still failing.
@tsnelson1 's solution fixes the problem.

**Comment by WI-FA** [comment]
@axtro Hi, maybe you can say me where is located the file of descompress-zip to make the change, thanks!
